// <auto-generated />
using System;
using Compass.DataService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Compass.DataService.Infrastructure.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20230718072414_updatecmod")]
    partial class updatecmod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Compass.Wasm.Shared.Data.ModuleData", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Discriminator");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasColumnName("Height");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<double>("Length")
                        .HasColumnType("float")
                        .HasColumnName("Length");

                    b.Property<int>("SidePanel")
                        .HasColumnType("int")
                        .HasColumnName("SidePanel");

                    b.Property<double>("Width")
                        .HasColumnType("float")
                        .HasColumnName("Width");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("ModulesData");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ModuleData");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KviData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.Property<bool>("Ansul")
                        .HasColumnType("bit")
                        .HasColumnName("Ansul");

                    b.Property<int>("AnsulDetector")
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetector");

                    b.Property<double>("AnsulDropDis1")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis1");

                    b.Property<double>("AnsulDropDis2")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis2");

                    b.Property<double>("AnsulDropDis3")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis3");

                    b.Property<double>("AnsulDropDis4")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis4");

                    b.Property<double>("AnsulDropDis5")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis5");

                    b.Property<int>("AnsulDropNumber")
                        .HasColumnType("int")
                        .HasColumnName("AnsulDropNumber");

                    b.Property<double>("AnsulDropToFront")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropToFront");

                    b.Property<int>("AnsulSide")
                        .HasColumnType("int")
                        .HasColumnName("AnsulSide");

                    b.Property<bool>("BackCj")
                        .HasColumnType("bit")
                        .HasColumnName("BackCj");

                    b.Property<bool>("BackToBack")
                        .HasColumnType("bit")
                        .HasColumnName("BackToBack");

                    b.Property<double>("CjSpigotToRight")
                        .HasColumnType("float")
                        .HasColumnName("CjSpigotToRight");

                    b.Property<bool>("CoverBoard")
                        .HasColumnType("bit")
                        .HasColumnName("CoverBoard");

                    b.Property<int>("DrainType")
                        .HasColumnType("int")
                        .HasColumnName("DrainType");

                    b.Property<double>("ExhaustSpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotDis");

                    b.Property<double>("ExhaustSpigotHeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotHeight");

                    b.Property<double>("ExhaustSpigotLength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotLength");

                    b.Property<int>("ExhaustSpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ExhaustSpigotNumber");

                    b.Property<double>("ExhaustSpigotWidth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotWidth");

                    b.Property<bool>("LedLogo")
                        .HasColumnType("bit")
                        .HasColumnName("LedLogo");

                    b.Property<double>("LightToFront")
                        .HasColumnType("float")
                        .HasColumnName("LightToFront");

                    b.Property<int>("LightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("LightType");

                    b.Property<bool>("Marvel")
                        .HasColumnType("bit")
                        .HasColumnName("Marvel");

                    b.Property<double>("MiddleToRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("MiddleToRight");

                    b.Property<double>("SpotLightDistance")
                        .HasColumnType("float")
                        .HasColumnName("SpotLightDistance");

                    b.Property<int>("SpotLightNumber")
                        .HasColumnType("int")
                        .HasColumnName("SpotLightNumber");

                    b.Property<bool>("WaterCollection")
                        .HasColumnType("bit")
                        .HasColumnName("WaterCollection");

                    b.HasDiscriminator().HasValue("KviData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KvvData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.Property<double>("ExhaustSpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotDis");

                    b.Property<double>("ExhaustSpigotHeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotHeight");

                    b.Property<double>("ExhaustSpigotLength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotLength");

                    b.Property<int>("ExhaustSpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ExhaustSpigotNumber");

                    b.Property<double>("ExhaustSpigotWidth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotWidth");

                    b.Property<int>("LightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("LightType");

                    b.Property<double>("MiddleToRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("MiddleToRight");

                    b.HasDiscriminator().HasValue("KvvData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KvfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KviData");

                    b.Property<double>("SupplySpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("SupplySpigotDis");

                    b.Property<int>("SupplySpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("SupplySpigotNumber");

                    b.HasDiscriminator().HasValue("KvfData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KwiData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KviData");

                    b.Property<double>("AnsulDetectorDis1")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis1");

                    b.Property<double>("AnsulDetectorDis2")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis2");

                    b.Property<double>("AnsulDetectorDis3")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis3");

                    b.Property<double>("AnsulDetectorDis4")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis4");

                    b.Property<double>("AnsulDetectorDis5")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis5");

                    b.Property<int>("AnsulDetectorEnd")
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetectorEnd");

                    b.Property<int>("AnsulDetectorNumber")
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetectorNumber");

                    b.Property<int>("WaterInlet")
                        .HasColumnType("int")
                        .HasColumnName("WaterInlet");

                    b.HasDiscriminator().HasValue("KwiData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UviData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KviData");

                    b.Property<bool>("Bluetooth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Bluetooth");

                    b.Property<int>("UvLightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("UvLightType");

                    b.HasDiscriminator().HasValue("UviData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.CmodiData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KwiData");

                    b.HasDiscriminator().HasValue("CmodiData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KwfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KwiData");

                    b.Property<double>("SupplySpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("SupplySpigotDis");

                    b.Property<int>("SupplySpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("SupplySpigotNumber");

                    b.HasDiscriminator().HasValue("KwfData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UwiData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KwiData");

                    b.Property<bool>("Bluetooth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Bluetooth");

                    b.Property<int>("UvLightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("UvLightType");

                    b.HasDiscriminator().HasValue("UwiData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UvfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.UviData");

                    b.Property<double>("SupplySpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("SupplySpigotDis");

                    b.Property<int>("SupplySpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("SupplySpigotNumber");

                    b.HasDiscriminator().HasValue("UvfData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.CmodfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KwfData");

                    b.HasDiscriminator().HasValue("CmodfData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UwfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.UwiData");

                    b.Property<double>("SupplySpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("SupplySpigotDis");

                    b.Property<int>("SupplySpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("SupplySpigotNumber");

                    b.HasDiscriminator().HasValue("UwfData");
                });
#pragma warning restore 612, 618
        }
    }
}
