// <auto-generated />
using System;
using Compass.DataService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Compass.DataService.Infrastructure.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Compass.Wasm.Shared.Data.ModuleData", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Discriminator");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasColumnName("Height");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<double>("Length")
                        .HasColumnType("float")
                        .HasColumnName("Length");

                    b.Property<int>("SidePanel")
                        .HasColumnType("int")
                        .HasColumnName("SidePanel");

                    b.Property<double>("Width")
                        .HasColumnType("float")
                        .HasColumnName("Width");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("ModulesData");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ModuleData");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Ceilings.CjData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.Property<int>("BcjSide")
                        .HasColumnType("int")
                        .HasColumnName("BcjSide");

                    b.Property<int>("CjSpigotDirection")
                        .HasColumnType("int")
                        .HasColumnName("CjSpigotDirection");

                    b.Property<double>("CjSpigotToRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("CjSpigotToRight");

                    b.Property<int>("GutterSide")
                        .HasColumnType("int")
                        .HasColumnName("GutterSide");

                    b.Property<int>("LeftBeamType")
                        .HasColumnType("int")
                        .HasColumnName("LeftBeamType");

                    b.Property<double>("LeftDbToRight")
                        .HasColumnType("float")
                        .HasColumnName("LeftDbToRight");

                    b.Property<double>("LeftEndDis")
                        .HasColumnType("float")
                        .HasColumnName("LeftEndDis");

                    b.Property<double>("LeftGutterWidth")
                        .HasColumnType("float")
                        .HasColumnName("LeftGutterWidth");

                    b.Property<int>("LksSide")
                        .HasColumnType("int")
                        .HasColumnName("LksSide");

                    b.Property<int>("RightBeamType")
                        .HasColumnType("int")
                        .HasColumnName("RightBeamType");

                    b.Property<double>("RightDbToLeft")
                        .HasColumnType("float")
                        .HasColumnName("RightDbToLeft");

                    b.Property<double>("RightEndDis")
                        .HasColumnType("float")
                        .HasColumnName("RightEndDis");

                    b.Property<double>("RightGutterWidth")
                        .HasColumnType("float")
                        .HasColumnName("RightGutterWidth");

                    b.HasDiscriminator().HasValue("CjData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Ceilings.KcjData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.Property<bool>("Ansul")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Ansul");

                    b.Property<int>("AnsulDetector")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetector");

                    b.Property<double>("AnsulDetectorDis1")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis1");

                    b.Property<double>("AnsulDetectorDis2")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis2");

                    b.Property<double>("AnsulDetectorDis3")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis3");

                    b.Property<double>("AnsulDetectorDis4")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis4");

                    b.Property<double>("AnsulDetectorDis5")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis5");

                    b.Property<int>("AnsulDetectorEnd")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetectorEnd");

                    b.Property<int>("AnsulDetectorNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetectorNumber");

                    b.Property<int>("AnsulSide")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulSide");

                    b.Property<int>("CeilingLightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("CeilingLightType");

                    b.Property<bool>("DomeSsp")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("DomeSsp");

                    b.Property<double>("ExhaustSpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotDis");

                    b.Property<double>("ExhaustSpigotHeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotHeight");

                    b.Property<double>("ExhaustSpigotLength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotLength");

                    b.Property<int>("ExhaustSpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ExhaustSpigotNumber");

                    b.Property<double>("ExhaustSpigotWidth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotWidth");

                    b.Property<int>("FilterBlindNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("FilterBlindNumber");

                    b.Property<double>("FilterLeft")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("FilterLeft");

                    b.Property<double>("FilterRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("FilterRight");

                    b.Property<int>("FilterSide")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("FilterSide");

                    b.Property<int>("FilterType")
                        .HasColumnType("int")
                        .HasColumnName("FilterType");

                    b.Property<bool>("Gutter")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Gutter");

                    b.Property<double>("GutterWidth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("GutterWidth");

                    b.Property<double>("HclLeft")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("HclLeft");

                    b.Property<double>("HclRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("HclRight");

                    b.Property<int>("HclSide")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("HclSide");

                    b.Property<bool>("Japan")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Japan");

                    b.Property<int>("LightCable")
                        .HasColumnType("int")
                        .HasColumnName("LightCable");

                    b.Property<bool>("Marvel")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Marvel");

                    b.Property<double>("MiddleToRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("MiddleToRight");

                    b.HasDiscriminator().HasValue("KcjData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Ceilings.KcwData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.Property<bool>("Ansul")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Ansul");

                    b.Property<int>("AnsulSide")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulSide");

                    b.Property<int>("CeilingLightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("CeilingLightType");

                    b.Property<int>("CeilingWaterInlet")
                        .HasColumnType("int")
                        .HasColumnName("CeilingWaterInlet");

                    b.Property<bool>("DomeSsp")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("DomeSsp");

                    b.Property<int>("DpSide")
                        .HasColumnType("int")
                        .HasColumnName("DpSide");

                    b.Property<double>("ExhaustSpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotDis");

                    b.Property<double>("ExhaustSpigotHeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotHeight");

                    b.Property<double>("ExhaustSpigotLength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotLength");

                    b.Property<int>("ExhaustSpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ExhaustSpigotNumber");

                    b.Property<double>("ExhaustSpigotWidth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotWidth");

                    b.Property<int>("FilterBlindNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("FilterBlindNumber");

                    b.Property<double>("FilterLeft")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("FilterLeft");

                    b.Property<double>("FilterRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("FilterRight");

                    b.Property<int>("FilterSide")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("FilterSide");

                    b.Property<bool>("Gutter")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Gutter");

                    b.Property<double>("GutterWidth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("GutterWidth");

                    b.Property<double>("HclLeft")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("HclLeft");

                    b.Property<double>("HclRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("HclRight");

                    b.Property<int>("HclSide")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("HclSide");

                    b.Property<bool>("Japan")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Japan");

                    b.Property<bool>("Marvel")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Marvel");

                    b.Property<double>("MiddleToRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("MiddleToRight");

                    b.HasDiscriminator().HasValue("KcwData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.CmodmData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("CmodmData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KviData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.Property<bool>("Ansul")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Ansul");

                    b.Property<int>("AnsulDetector")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetector");

                    b.Property<double>("AnsulDropDis1")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis1");

                    b.Property<double>("AnsulDropDis2")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis2");

                    b.Property<double>("AnsulDropDis3")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis3");

                    b.Property<double>("AnsulDropDis4")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis4");

                    b.Property<double>("AnsulDropDis5")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropDis5");

                    b.Property<int>("AnsulDropNumber")
                        .HasColumnType("int")
                        .HasColumnName("AnsulDropNumber");

                    b.Property<double>("AnsulDropToFront")
                        .HasColumnType("float")
                        .HasColumnName("AnsulDropToFront");

                    b.Property<int>("AnsulSide")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulSide");

                    b.Property<bool>("BackCj")
                        .HasColumnType("bit")
                        .HasColumnName("BackCj");

                    b.Property<bool>("BackToBack")
                        .HasColumnType("bit")
                        .HasColumnName("BackToBack");

                    b.Property<double>("CjSpigotToRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("CjSpigotToRight");

                    b.Property<bool>("CoverBoard")
                        .HasColumnType("bit")
                        .HasColumnName("CoverBoard");

                    b.Property<int>("DrainType")
                        .HasColumnType("int")
                        .HasColumnName("DrainType");

                    b.Property<double>("ExhaustSpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotDis");

                    b.Property<double>("ExhaustSpigotHeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotHeight");

                    b.Property<double>("ExhaustSpigotLength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotLength");

                    b.Property<int>("ExhaustSpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ExhaustSpigotNumber");

                    b.Property<double>("ExhaustSpigotWidth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotWidth");

                    b.Property<bool>("LedLogo")
                        .HasColumnType("bit")
                        .HasColumnName("LedLogo");

                    b.Property<double>("LightToFront")
                        .HasColumnType("float")
                        .HasColumnName("LightToFront");

                    b.Property<int>("LightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("LightType");

                    b.Property<bool>("Marvel")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Marvel");

                    b.Property<double>("MiddleToRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("MiddleToRight");

                    b.Property<double>("SpotLightDistance")
                        .HasColumnType("float")
                        .HasColumnName("SpotLightDistance");

                    b.Property<int>("SpotLightNumber")
                        .HasColumnType("int")
                        .HasColumnName("SpotLightNumber");

                    b.Property<bool>("WaterCollection")
                        .HasColumnType("bit")
                        .HasColumnName("WaterCollection");

                    b.HasDiscriminator().HasValue("KviData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KvvData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.Property<double>("ExhaustSpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotDis");

                    b.Property<double>("ExhaustSpigotHeight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotHeight");

                    b.Property<double>("ExhaustSpigotLength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotLength");

                    b.Property<int>("ExhaustSpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("ExhaustSpigotNumber");

                    b.Property<double>("ExhaustSpigotWidth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("ExhaustSpigotWidth");

                    b.Property<int>("LightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("LightType");

                    b.Property<double>("MiddleToRight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("MiddleToRight");

                    b.HasDiscriminator().HasValue("KvvData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UvimData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("UvimData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KvcData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KvcData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KvcUvData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KvcUvData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KvcUvWwData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KvcUvWwData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KvcWwData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KvcWwData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KveData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KveData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KveUvData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KveUvData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KveUvWwData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KveUvWwData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KveWwData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KveWwData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KvrData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KvrData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.KvwData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.ModuleData");

                    b.HasDiscriminator().HasValue("KvwData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Ceilings.UcjData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Ceilings.KcjData");

                    b.Property<int>("UvLightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("UvLightType");

                    b.HasDiscriminator().HasValue("UcjData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Ceilings.UcwData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Ceilings.KcwData");

                    b.Property<double>("BaffleSensorDis1")
                        .HasColumnType("float")
                        .HasColumnName("BaffleSensorDis1");

                    b.Property<double>("BaffleSensorDis2")
                        .HasColumnType("float")
                        .HasColumnName("BaffleSensorDis2");

                    b.Property<int>("BaffleSensorNumber")
                        .HasColumnType("int")
                        .HasColumnName("BaffleSensorNumber");

                    b.Property<int>("UvLightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("UvLightType");

                    b.HasDiscriminator().HasValue("UcwData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KvfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KviData");

                    b.Property<double>("SupplySpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("SupplySpigotDis");

                    b.Property<int>("SupplySpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("SupplySpigotNumber");

                    b.HasDiscriminator().HasValue("KvfData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KwiData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KviData");

                    b.Property<double>("AnsulDetectorDis1")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis1");

                    b.Property<double>("AnsulDetectorDis2")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis2");

                    b.Property<double>("AnsulDetectorDis3")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis3");

                    b.Property<double>("AnsulDetectorDis4")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis4");

                    b.Property<double>("AnsulDetectorDis5")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("AnsulDetectorDis5");

                    b.Property<int>("AnsulDetectorEnd")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetectorEnd");

                    b.Property<int>("AnsulDetectorNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("AnsulDetectorNumber");

                    b.Property<int>("WaterInlet")
                        .HasColumnType("int")
                        .HasColumnName("WaterInlet");

                    b.HasDiscriminator().HasValue("KwiData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UviData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KviData");

                    b.Property<bool>("Bluetooth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Bluetooth");

                    b.Property<int>("UvLightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("UvLightType");

                    b.HasDiscriminator().HasValue("UviData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.UL.ChData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KvvData");

                    b.HasDiscriminator().HasValue("ChData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KchData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KvfData");

                    b.HasDiscriminator().HasValue("KchData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.CmodiData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KwiData");

                    b.HasDiscriminator().HasValue("CmodiData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.KwfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KwiData");

                    b.Property<double>("SupplySpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("SupplySpigotDis");

                    b.Property<int>("SupplySpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("SupplySpigotNumber");

                    b.HasDiscriminator().HasValue("KwfData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UwiData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KwiData");

                    b.Property<bool>("Bluetooth")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bit")
                        .HasColumnName("Bluetooth");

                    b.Property<int>("UvLightType")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("UvLightType");

                    b.HasDiscriminator().HasValue("UwiData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UvfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.UviData");

                    b.Property<double>("SupplySpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("SupplySpigotDis");

                    b.Property<int>("SupplySpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("SupplySpigotNumber");

                    b.HasDiscriminator().HasValue("UvfData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.CmodfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.KwfData");

                    b.HasDiscriminator().HasValue("CmodfData");
                });

            modelBuilder.Entity("Compass.Wasm.Shared.Data.Hoods.UwfData", b =>
                {
                    b.HasBaseType("Compass.Wasm.Shared.Data.Hoods.UwiData");

                    b.Property<double>("SupplySpigotDis")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("float")
                        .HasColumnName("SupplySpigotDis");

                    b.Property<int>("SupplySpigotNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("SupplySpigotNumber");

                    b.HasDiscriminator().HasValue("UwfData");
                });
#pragma warning restore 612, 618
        }
    }
}
